### ISSUE TITLE
Implement extra math functions

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychojs#128]
Add `sum()` and `round()` helpers as found on Wakefield's [Python to JavaScript Crib Sheet &rsaquo;](https://docs.google.com/document/d/13jp0QAqQeFlYSjeZS0fDInvgaDzBXjGQNe4VNKbbNHQ)

**Comment by tpronk** [comment]
I ran some tests of sum. I noticed the following:
`sum(6)` returned 0, but I would expect it to return 6.

Also, I'd recommend to throw an error if any values are passed that aren't numeric, instead of parsing them to a number. 
More cocretely, if I run this:
`sum(['a1',2]`
I'd recommend it not to return 3, but fail with an error.

**Comment by thewhodidthis** [comment]
Thanks @tpronk, all of what you describe is both logical and doable, just different from the spec I had to work with :smirk:

**Comment by thewhodidthis** [comment]
https://gist.github.com/thewhodidthis/134950d285df2da12142786dddc013f3#file-sum-js
