### ISSUE TITLE
online pseudorandomization does not work

### ISSUE THREAD

**Issue by JensBoelte** [psychopy/psychojs#197]
I try to randomize trials in a anchoring experiment in the following manner. The first and the last trial of a block are fixed. I want to randomize the trials in between. This works offline but not online. The array index which refers to rows in an excel file has been randomized in a code element preceding the routine

![grafik](https://user-images.githubusercontent.com/59830573/94815415-c9f64780-03fa-11eb-929a-e0e54735f99c.png)

![grafik](https://user-images.githubusercontent.com/59830573/94815534-ef835100-03fa-11eb-873c-36df622ce9e6.png)

However, no randomization online. The array index seems to be "ignored" here (
`trialList: TrialHandler.importConditions(psychoJS.serverManager, (AbrufListe + ".xlsx"), index),`

[Link to the experiment](https://gitlab.pavlovia.org/jens.boelte/falsememexp2)

Any idea why this does not work online?

Cheers Jens

**Comment by thewhodidthis** [comment]
@JensBoelte Many thanks for flagging, I was unable to access the link you posted (404). Is the project set to private maybe? Would it be possible to grant me developer access to your repo on Pavlovia so that I can investigate some more? Thanks, s.

**Comment by JensBoelte** [comment]
@thewhodidthis You have been added as a developer.

**Comment by JensBoelte** [comment]
@thewhodidthis Well, it still does not work for me. Perhaps the forking and syncing did go wrong? Anyway, when I initialize the variable in the CodeInit routine the behavior does not change. Still, no randomization. The old/new items are always in the same order. Cheers Jens

**Comment by JensBoelte** [comment]
BTW, I am using the same approach in a different experiment (https://gitlab.pavlovia.org/jens.boelte/changeblindnessexp3) with no randomization online but working offline.

**Comment by thewhodidthis** [comment]
@JensBoelte No problem, it could very well be that out existing `shuffle()` needs tweaking. I've added a fresh implementation in my fork below. Does that work any better?

[run.pavlovia.org/thewhodidthis/falsememexp2/html &rarr;](https://run.pavlovia.org/thewhodidthis/falsememexp2/html/)

**Comment by JensBoelte** [comment]
@thewhodidthis Thanks a lot four your help on a Saturday. Alas, your fork did not solve the problem. Same as before, items are not shuffled.

**Comment by JensBoelte** [comment]
I think that we have identified the problem. If we change the line
`trialList: TrialHandler.importConditions(psychoJS.serverManager, (AbrufListe + ".xlsx"), index),`
to
`trialList: TrialHandler.importConditions(psychoJS.serverManager, (AbrufListe + ".xlsx"), index.toString()),`
the randomization works.
At the moment, we do this by hand in the JavaScript code stored online. Suggestions are welcome on how to code this properly in the JavaScript part in Builder. Simply making the index to a string index did not work (`index.toString()`).

Cheers Jens

**Comment by thewhodidthis** [comment]
@JensBoelte No worries at all, I have prepared [an example script](https://repl.it/repls/CarpalFreshAdmin) that hopefully demonstrates `shuffle()` is shuffling as expected. If your intention is to insert a zero at the beginning of your `index` array right after rearranging its contents, could you try `index.unshift(0)` instead of `index.unshift(0, 0)`? Alternatively, you could try `index.splice(0, 0, 0)`. That would be more in line with Python's `insert()`, in that you pass it an argument for the index of the element to be added, which in this case would be 0. Hope that helps some, please let me know if you need more support, x

**Comment by JensBoelte** [comment]
@thewhodidthis  I notice that `unshift(0,0)` inserted more 0s than I wanted. This is already corrected. I think that  `shuffle()` is working as expected as long as you get the TrialHandler to read the index as a string.

Cheers Jens

**Comment by thewhodidthis** [comment]
@JensBoelte No problem, let me do some more digging, x

**Comment by thewhodidthis** [comment]
Dear @JensBoelte, as it happens it's a bug and you were absolutely right to insist. I'm sorry I was unable to look into this in more detail sooner. The problem is with how `util.selectFromArray()` was treating array input, pulling out the right elements but in their original order. I have [fixed that in my fork](https://gitlab.pavlovia.org/thewhodidthis/falsememexp2/blob/master/html/lib/util-2020.2-patch.js#L951) and should be issuing the relevant PR very soon, but it might take a few days for it to reach Pavlovia's servers. Thanks again for helping us improve PsychoJS. Please let me know if you need more support, x

Look for edits inside the main script and lib folder: [gitlab.pavlovia.org/thewhodidthis/falsememexp2](https://gitlab.pavlovia.org/thewhodidthis/falsememexp2)
Preview: [run.pavlovia.org/thewhodidthis/falsememexp2/html &rarr;](https://run.pavlovia.org/thewhodidthis/falsememexp2/html)
