### ISSUE TITLE
data/util: Improve browser compatibility for turnSquareBracketsIntoArrays() 

### ISSUE THREAD

**Issue by thewhodidthis** [psychopy/psychojs#226]
Replace `String.matchAll()`

**Comment by wakecarter** [comment]
Sorry -- but I'm not sure what this thread means. Is there anything I can do to run experiments on mobile devices or do I have to just wait for someone else to fix PsychoJS? What commands/components use String.matchAll()?

**Comment by thewhodidthis** [comment]
No problem, the helper in question is used for parsing array looking cell entries inside of [`TrialHandler`](https://github.com/psychopy/psychojs/blob/85f77e1b394171a9067c9cc21d6e116bbbb0ab75/js/data/TrialHandler.js#L471). As things stand it should work with [a fairly reasonable range of browsers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#Browser_compatibility). To improve browser compatibility one would need to factor away from that [`input.matchAll()`](https://github.com/psychopy/psychojs/blob/master/js/util/Util.js#L973
) call. You are welcome to submit a PR if you like, or just wait a few more days?

**Comment by wakecarter** [comment]
Sorry -- I feel like I'm outside of my comfort zone here.

"parsing array looking cell entries inside of TrialHandler" = any experiment reading Excel conditions files? Would this apply to csv files too? 

"it should work with a fairly reasonable range of browsers. " = when fixed in a few more days as opposed to now?

"factor away from that input.matchAll() call" = i.e. avoid using Excel files?

"PR" = pull request? Do you mean that the fix is there but I need to either manually update my version of PsychoPy (in which case I'd need to learn how) or wait for a new version (2020.2.9?) to be released?

Since I'm current working on half a dozen or more experiments then I might just switch my attention to ones that aren't trying to run on a mobile for the next few days.

**Comment by thewhodidthis** [comment]
No problem, helper function yes, .cvs files too yes, a fairly reasonable range of browsers as things stand, factor away as in rework the code to not assume a `String.prototype.matchAll()` method is available. PR stands for pull request yes, as in a proposed fix. Please @wakecarter, I do have a fix in mind, I just need a little more time to implement it and for sure the patch should be available on Pavlovia without you having to update PsychoPy. Please let me know if you need more details, thanks, x
