### ISSUE TITLE
Have getActualFrameRate() measure frameRate

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#257]
Presently, [getActualFrameRate()](https://github.com/psychopy/psychojs/blob/cf0f2191f1d4a528010441e1f7888baf79008100/js/core/Window.js#L152) returns 60 by default. It could be handy if PsychoJS would detect the refresh rate by measuring the average interval between successive calls by requestAnimationFrame for a number of refreshes. This experiment may provide a starting point. https://gitlab.pavlovia.org/tpronk/demo_refresh_rate/

**Comment by peircej** [comment]
In particular, in PsychoPy this is done relatively early; after a pause of a second or so to let the window initialisation complete, but before rendering stimuli so that we measure the frame rate with no load (I have wondered about having it output the frame rate on each trial separately but there are issues with that)
