### ISSUE TITLE
Is there a limit to the size of movie that can be played?

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#37]
*Warning: Unpleasant content in one of the video files*

A user wants to play movies from Pavlovia. They upload ok, but the experiment freezes when you click "Ok" to begin, and then the Pavlovia dashboard also freezes. 

*project deleted* 

If there is a preferred file type (e.g., not .wmv) or file size limit, perhaps we can put this as a warning, or document it.

**Comment by dvbridges** [comment]
Also reported by another user on Discourse:

https://discourse.psychopy.org/t/6986/2

**Comment by apitiot** [comment]
I've contacted Ferenc regarding the units issue, which was solved by changing them to "height", as discussed on the forum.

I am afraid that the freezing problem cannot be reproduced any longer since the experiment has been deleted. David: would you like to create another one so I can give it a try?

**Comment by dvbridges** [comment]
Thanks @apitiot, I have had a look at the users experiment again. The main issue was the format of the video files being .wmv. After converting the files to mp4 format, the problem disappeared. Closing the issue.
