### ISSUE TITLE
Support for Internet Explorer 11

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#38]

**Comment by peircej** [comment]
Parts of pavlovia.org do now work with IE11 but several parts don't and we're expecting never to support it with PsychoJS lib I think. Should we detect it and simply bring up a message that IE is not suported and please use Firefox, Chrome or Edge?

**Comment by apitiot** [comment]
There is now an error message for users attempting to run an experiment in Internet Explorer (10 or 11), while I am figuring out how to make it run properly. I am edging closer but it is tricky!

**Comment by peircej** [comment]
Oh, you're actually getting the experiments to run as well?! That's even better if it's possible (I thought it couldn't be done because of the libs we were using)

**Comment by apitiot** [comment]
There are two versions of the PsychoJS library: one for modern browsers (using modules) and one for legacy browsers (i.e. Internet Explorer). This is the reason why PsychoPy generates two scripts, e.g. stroop.js and stroopNoModule.js. For the legacy browser version of PsyhoJS, I am using all sorts of tricks to transpile the code and package it into something that can run on IE10 and IE11. I work on it every so often, since it is not a high priority task. But certainly I am aiming to make experiments run in IE11 before the official end of the Wellcome Trust grant.

**Comment by peircej** [comment]
Oh, OK, that's great!

**Comment by peircej** [comment]
This is done, right?

**Comment by dvbridges** [comment]
@peircej , works for me using PsychoPy 2020.1.3.

**Comment by apitiot** [comment]
I have just trieds demos/stroop on IE11 on my end, and it is also working like a charm.
