### ISSUE TITLE
two bugs that happen when you want to dynamically set the position and size of a rectangle shape (and possibly other shapes) from a csv

### ISSUE THREAD

**Issue by overly-excessive** [psychopy/psychojs#44]
Hello!
I found two bugs that occur when i want to dynamically set the position and/or size of a rectangle (shape stimulus). These bugs only happen in the online javascript version and not when i run the experiment locally in python

The first bug happens when the component is being initialized in the beginning of the experiment. PsychoJS is trying to set the position and size attributes with the variable, instead of giving them a placeholder value for the time being, which results in a reference error because the variable hasnt yet been pulled from the csv file.

The second bug is specifically related to the rectangle subclass (maybe some other shapes will have it as well). It happens when the size attribute is being dynamically adjusted at the beginning of the routine. PsychoJS is trying to use the setSize setter method, but it doesnt work because the rectangle has specific setWidth and setHeight methods, which have to be used instead.

This is my first time reporting bugs like this so i hope i provided enough info for you to fix the issue, i just thought since i spent my day trying to make my experiment work there might as well be some use from it for you guys as well :)

**Comment by peircej** [comment]
Thanks @overly-excessive for contributing. I think @dvbridges might be able to manage these - they both look like issues with the way that Builder outputs the code, rather than issues in the PsychoJS lib itself. 
Maybe you could point us to an example experiment with the fail in it (at least for the first bug - the second bug is straightforwards)
thanks

**Comment by overly-excessive** [comment]
Here is a link to the commit where i manually fix both bugs in the .js file of my experiment

https://gitlab.pavlovia.org/gobochul/heptopod/commit/8da3e37636461a8bb5d33727916bf587fa385356

**Comment by dvbridges** [comment]
Cheers @peircej , the first issue is already fixed in master [1] but probably got missed from the release because of the commit msg prefix and because it contained unrelated fixes. In the fix below, polygon is initiated with default init values. 

I will make a pull request for the second issue today.

[1] https://github.com/psychopy/psychopy/pull/2251/commits/400d6110553fc722e687d80b9b6fd6180ddef4c0

**Comment by peircej** [comment]
The issues are both fixed in the repositories. The first was released in PsychoPy 3.1.0 and the second has not yet made it into the online version of psychojs but will do when #56 is complete
