### ISSUE TITLE
Builder Polygons are created as Rects

### ISSUE THREAD

**Issue by kastman** [psychopy/psychojs#58]
Hi @apitiot - 

Seems like ShapeStims in builder (3.0.5) are always compiled as Rect stims, although ShapeStim is a valid component and already exists. Is this something that you've already updated without pushing back to github? Any reason for this builder shortcut?

Super-basic example of a "triangle" shape stim compiled as a Rect with a coded shapestim side-by-side:

https://run.pavlovia.org/kastman/shapedemo/html/index.html

**Comment by peircej** [comment]
The part where Builder outputs to JS is actually handled mostly by @dvbridges rather than @apitiot 

@dvbridges and I had discussed adding some more explicit shapes, initially to psychojs and then to the Builder outputs. That would be more in keeping with the Python lib, so that users could use a wider range of shapes, but we hadn't got round to it yet.

**Comment by dvbridges** [comment]
Hi @kastman , from PsychoPy 3.1.0, line and triangle stim are created using ShapeStim. You can also define shapes with nVertices <=4, equivalent to line, triangle and rect stim - having shapes with higher nVertices is work in progress. Soon, we should also add current known shapes to the JS output (e.g., cross, star).

**Comment by kastman** [comment]
Awesome @dvbridges - thanks! I was just following the auto-update so hadn't seen 3.1. 

The only other shape I'd add is a circle (I usually use 60 vertices but that's totally just rule-of-thumb). If I get around to it I might push back. Any reason why the js filename is `Rect` instead of `RectStim` like the other stim files in `visual`? Thanks!
