### ISSUE TITLE
Problems with MovieStim resulting in the readpixels error

### ISSUE THREAD

**Issue by peircej** [psychopy/psychojs#77]
I wonder if moviestim is a place having memory leaks. See this post regarding readpixels error after a feew minutes (for some participants)

https://discourse.psychopy.org/t/technical-issues-when-running-experiment-on-pavlovia/11389

**Comment by apitiot** [comment]
I believe that the two issues, memory leaks and readpixels, are unrelated.

I have just back-ported a readPixels fix that I had previously put in place for more recent versions of the library to core.js, which is what the gentleman is using. So that should be sorted.

I will be looking at memory leaks next week.
